name: Deploy feature branch

on: [pull_request]

jobs:
  rurl:
    name: Publish feature branch url
    runs-on: ubuntu-latest
    steps:
      # strip 'refs/heads/' from GITHUB_REF and export as ${{ steps.get_branch.outputs.branch }}
      - name: Get branch name
        env:
          BRANCH_REF: ${{ github.head_ref }}
        id: get_branch
        run: echo "::set-output name=branch::${BRANCH_REF##*/}"
      - name: Publish url in PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          msg: Deployed to https://${{ steps.get_branch.outputs.branch }}.${{ secrets.TEST_DOMAIN }}
          check_for_duplicate_msg: false

