name: Deploy to staging

# on:
#   push:
#     branches:
#       - master

# Test only
on: [pull_request]

jobs:
  run-ci:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run lint
    - run: make
    - run: make source-package
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        SOURCE: "source_package/jitsi-meet"
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        TARGET: ${{ secrets.DEPLOY_TARGET }}
